// Romanian Counties (Județe) + București
export const ROMANIAN_COUNTIES = [
  { code: "AB", name: "Alba" },
  { code: "AR", name: "Arad" },
  { code: "AG", name: "Argeș" },
  { code: "BC", name: "Bacău" },
  { code: "BH", name: "Bihor" },
  { code: "BN", name: "Bistrița-Năsăud" },
  { code: "BT", name: "Botoșani" },
  { code: "BR", name: "Brăila" },
  { code: "BV", name: "Brașov" },
  { code: "B", name: "București" },
  { code: "BZ", name: "Buzău" },
  { code: "CL", name: "Călărași" },
  { code: "CS", name: "Caraș-Severin" },
  { code: "CJ", name: "Cluj" },
  { code: "CT", name: "Constanța" },
  { code: "CV", name: "Covasna" },
  { code: "DB", name: "Dâmbovița" },
  { code: "DJ", name: "Dolj" },
  { code: "GL", name: "Galați" },
  { code: "GR", name: "Giurgiu" },
  { code: "GJ", name: "Gorj" },
  { code: "HR", name: "Harghita" },
  { code: "HD", name: "Hunedoara" },
  { code: "IL", name: "Ialomița" },
  { code: "IS", name: "Iași" },
  { code: "IF", name: "Ilfov" },
  { code: "MM", name: "Maramureș" },
  { code: "MH", name: "Mehedinți" },
  { code: "MS", name: "Mureș" },
  { code: "NT", name: "Neamț" },
  { code: "OT", name: "Olt" },
  { code: "PH", name: "Prahova" },
  { code: "SJ", name: "Sălaj" },
  { code: "SM", name: "Satu Mare" },
  { code: "SB", name: "Sibiu" },
  { code: "SV", name: "Suceava" },
  { code: "TR", name: "Teleorman" },
  { code: "TM", name: "Timiș" },
  { code: "TL", name: "Tulcea" },
  { code: "VL", name: "Vâlcea" },
  { code: "VS", name: "Vaslui" },
  { code: "VN", name: "Vrancea" },
];

// Major cities by county for easier selection
export const ROMANIAN_CITIES_BY_COUNTY: Record<string, string[]> = {
  AB: ["Alba Iulia", "Sebeș", "Aiud", "Blaj", "Ocna Mureș", "Cugir"],
  AR: ["Arad", "Ineu", "Lipova", "Pecica", "Chișineu-Criș"],
  AG: ["Pitești", "Câmpulung", "Curtea de Argeș", "Mioveni", "Costești"],
  BC: ["Bacău", "Onești", "Moinești", "Comănești", "Buhuși"],
  BH: ["Oradea", "Salonta", "Marghita", "Beiuș", "Valea lui Mihai"],
  BN: ["Bistrița", "Beclean", "Năsăud", "Sângeorz-Băi"],
  BT: ["Botoșani", "Dorohoi", "Darabani", "Flămânzi", "Săveni"],
  BR: ["Brăila", "Ianca", "Însurăței", "Faurei"],
  BV: ["Brașov", "Făgăraș", "Săcele", "Codlea", "Râșnov", "Zărnești"],
  B: [
    "București",
    "Sectorul 1",
    "Sectorul 2",
    "Sectorul 3",
    "Sectorul 4",
    "Sectorul 5",
    "Sectorul 6",
  ],
  BZ: ["Buzău", "Râmnicu Sărat", "Nehoiu", "Pogoanele"],
  CL: ["Călărași", "Oltenița", "Lehliu Gară", "Budești"],
  CS: ["Reșița", "Caransebeș", "Lugoj", "Moldova Nouă", "Oțelu Roșu"],
  CJ: ["Cluj-Napoca", "Turda", "Dej", "Câmpia Turzii", "Gherla"],
  CT: ["Constanța", "Mangalia", "Medgidia", "Năvodari", "Cernavodă"],
  CV: ["Sfântu Gheorghe", "Târgu Secuiesc", "Covasna", "Băile Tușnad"],
  DB: ["Târgoviște", "Moreni", "Pucioasa", "Găești", "Titu"],
  DJ: ["Craiova", "Băilești", "Calafat", "Filiași", "Dăbuleni"],
  GL: ["Galați", "Tecuci", "Târgu Bujor", "Berești"],
  GR: ["Giurgiu", "Bolintin-Vale", "Mihăilești"],
  GJ: ["Târgu Jiu", "Motru", "Rovinari", "Turceni", "Bumbești-Jiu"],
  HR: ["Miercurea Ciuc", "Odorheiu Secuiesc", "Gheorgheni", "Toplița"],
  HD: ["Deva", "Hunedoara", "Petroșani", "Lupeni", "Vulcan", "Petrila"],
  IL: ["Slobozia", "Fetești", "Urziceni", "Amara", "Țăndărei"],
  IS: ["Iași", "Pașcani", "Târgu Frumos", "Hârlău", "Podu Iloaiei"],
  IF: [
    "Buftea",
    "Otopeni",
    "Voluntari",
    "Pantelimon",
    "Popești-Leordeni",
    "Chitila",
  ],
  MM: [
    "Baia Mare",
    "Sighetu Marmației",
    "Borșa",
    "Târgu Lăpuș",
    "Săliștea de Sus",
  ],
  MH: ["Drobeta-Turnu Severin", "Orșova", "Vânju Mare", "Strehaia"],
  MS: ["Târgu Mureș", "Reghin", "Sighișoara", "Târnăveni", "Luduș"],
  NT: ["Piatra Neamț", "Roman", "Târgu Neamț", "Bicaz", "Roznov"],
  OT: ["Slatina", "Caracal", "Balș", "Corabia", "Piatra Olt"],
  PH: ["Ploiești", "Câmpina", "Băicoi", "Azuga", "Bușteni", "Sinaia"],
  SJ: ["Zalău", "Șimleu Silvaniei", "Jibou", "Cehu Silvaniei"],
  SM: ["Satu Mare", "Carei", "Negrești-Oaș", "Tășnad", "Livada"],
  SB: ["Sibiu", "Mediaș", "Cisnădie", "Agnita", "Avrig"],
  SV: [
    "Suceava",
    "Fălticeni",
    "Rădăuți",
    "Câmpulung Moldovenesc",
    "Vatra Dornei",
  ],
  TR: ["Alexandria", "Rosiori de Vede", "Turnu Măgurele", "Zimnicea"],
  TM: ["Timișoara", "Lugoj", "Caransebeș", "Sânnicolau Mare", "Jimbolia"],
  TL: ["Tulcea", "Măcin", "Isaccea", "Sulina", "Babadag"],
  VL: ["Râmnicu Vâlcea", "Drăgășani", "Călimănești", "Băile Olănești"],
  VS: ["Vaslui", "Bârlad", "Huși", "Negrești", "Murgeni"],
  VN: ["Focșani", "Adjud", "Panciu", "Mărășești", "Odobești"],
};

// Most common cities for quick access
export const MAJOR_ROMANIAN_CITIES = [
  "București",
  "Cluj-Napoca",
  "Timișoara",
  "Iași",
  "Constanța",
  "Craiova",
  "Brașov",
  "Galați",
  "Ploiești",
  "Oradea",
  "Brăila",
  "Arad",
  "Pitești",
  "Sibiu",
  "Bacău",
  "Târgu Mureș",
  "Baia Mare",
  "Buzău",
  "Botoșani",
  "Satu Mare",
  "Râmnicu Vâlcea",
  "Drobeta-Turnu Severin",
  "Piatra Neamț",
  "Suceava",
  "Târgu Jiu",
  "Tulcea",
  "Vaslui",
  "Focșani",
  "Zalău",
  "Alba Iulia",
  "Bistrița",
  "Călărași",
  "Deva",
  "Giurgiu",
  "Hunedoara",
  "Miercurea Ciuc",
  "Reșița",
  "Sfântu Gheorghe",
  "Slatina",
  "Slobozia",
  "Târgoviște",
  "Târgu Neamț",
];

export type County = {
  code: string;
  name: string;
};

export type AddressData = {
  country: string;
  county: string;
  countyCode?: string;
  city: string;
  street: string;
  number: string;
  postalCode?: string;
  coordinates?: {
    lat: number;
    lng: number;
  };
};
